name: Sonar Analysis

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environmnet'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - sit   
          - uat
          - staging
          - performance
          - production
          - dr
          - Dev
          - SIT   
          - UAT
          - Staging
          - Performance
          - Production
          - DR
          - Prod
          - Sonar Test
          - Prod test
          - Test09122
          - Workflow 
          - Workflow 1
          - Evn Test 
          - Test09
          - Dev Github
          - Test10
          - Test Dev
  workflow_call:

    
jobs:
  sonar-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Environment name
        run: echo "Deploying to environment:" ${{ github.event.inputs.environment }}
